const effects=['burn','bleed','freeze','slow','crippled','hex'];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/\r?\n/g,'\\n');
const val=id=>$('#'+id).value.trim(); const num=v=>v===''?null:Number(v);
function addUpgrade(data={}){const node=$('#upgradeTemplate').content.firstElementChild.cloneNode(true);effects.forEach(e=>{const l=document.createElement('label');l.className='check';l.innerHTML=`<input type="checkbox" data-effect="${e}"> ${e[0].toUpperCase()+e.slice(1)}`;node.querySelector('.checks').append(l)});Object.entries(data).forEach(([k,v])=>{const el=node.querySelector(`[data-key="${k}"],[data-effect="${k}"]`);if(el)el.type==='checkbox'?el.checked=v:el.value=v});node.querySelector('.remove').onclick=()=>{node.remove();renumber();update()};node.querySelector('.copy-effects').onclick=()=>{const rows=$$('.upgrade'),i=rows.indexOf(node);if(i<1)return;effects.forEach(e=>node.querySelector(`[data-effect=${e}]`).checked=rows[i-1].querySelector(`[data-effect=${e}]`).checked);update()};node.addEventListener('input',update);$('#upgrades').append(node);renumber();update()}
function renumber(){$$('.upgrade').forEach((r,i)=>{r.querySelector('.upgrade-title').textContent=i===0?'Deployment':`Upgrade ${i}`;r.querySelector('.remove').hidden=i===0;r.querySelector('.copy-effects').hidden=i===0})}
function addPassive(data={}){const n=$('#passiveTemplate').content.firstElementChild.cloneNode(true);Object.entries(data).forEach(([k,v])=>n.querySelector(`[data-key=${k}]`).value=v);n.querySelector('.remove-passive').onclick=()=>{n.remove();update()};n.addEventListener('input',update);$('#passives').append(n);update()}
function readUpgrades(){return $$('.upgrade').map(r=>{const o={};r.querySelectorAll('[data-key]').forEach(x=>o[x.dataset.key]=x.value.trim());effects.forEach(e=>o[e]=r.querySelector(`[data-effect=${e}]`).checked);return o})}
function fmtRange(a,b){return a===b?String(a):`${a} -> ${b}`} function money(n){return Number(n).toLocaleString('en-US')+'$'}
function line(k,v){return `    ${k} = "${esc(v)}",`}
function generate(){const u=readUpgrades(),valid=u.filter(x=>x.damage!==''&&x.range!==''&&x.spa!=='');const first=valid[0],last=valid.at(-1);const used=effects.filter(e=>u.some(x=>x[e]));const out=['return {',`["${esc(val('unitName')||'Unit Name')}"] = {`,line('rarity',val('rarity')),line('element',val('element')),line('subtype',val('subtype')),line('towertype',val('towerType')),line('maxplacement',val('placement'))];if(first){out.push(line('damage',fmtRange(first.damage,last.damage)),line('range',fmtRange(first.range,last.range)),line('spa',fmtRange(first.spa,last.spa)),line('deploycost',money(first.cost||0)),line('totalcost',money(u.reduce((s,x)=>s+(num(x.cost)||0),0))))}out.push(line('image',val('image')));if(used.length<2)out.push(line('statuseffect',used.length?used[0][0].toUpperCase()+used[0].slice(1):'None'));else out.push(`    statuseffect = {${used.map(e=>`"${e[0].toUpperCase()+e.slice(1)}"`).join(', ')}},`);const attacks=u.map(x=>x.attack).filter(Boolean).filter((x,i,a)=>!i||x!==a[i-1]);out.push(line('aoetype',attacks.length?attacks.join(' -> '):''),line('imagecaption',val('caption')),line('overview',val('overview')));$$('.passive').forEach((p,i)=>{const n=i+1,d=p.querySelector('[data-key=description]').value.trim();if(d){out.push(line(`passive${n}_name`,p.querySelector('[data-key=name]').value.trim()),line(`passive${n}`,d),line(`passive${n}_upgrade`,p.querySelector('[data-key=upgrade]').value.trim()))}});if(val('ability'))out.push(line('ability_name',val('abilityName')),line('ability',val('ability')),line('ability_upgrade',val('abilityUpgrade')),line('ability_cooldown',val('abilityCooldown')));out.push('    upgrades = {');u.forEach((x,i)=>{const p=[`upgrade_cost = ${num(x.cost)??0}`,`damage = ${num(x.damage)??0}`,`range = ${num(x.range)??0}`,`spa = ${num(x.spa)??0}`];if(i===0)p.push(`placement = ${num(val('placement'))??0}`,`tower_type = "${esc(val('towerType'))}"`,`attack_type = "${esc(x.attack)}"`);else if(x.attack&&x.attack!==u[i-1].attack)p.push(`aoe_change = "${esc(x.attack)}"`);if(x.text)p.push(`text_line_1 = "${esc(x.text)}"`);effects.forEach(e=>{if(x[e])p.push(`${e} = "yes"`)});out.push(`        { ${p.join(', ')}},`)});out.push('    }','  },','}');return out.join('\n')}
function save(){const data={fields:{},upgrades:readUpgrades(),passives:$$('.passive').map(p=>Object.fromEntries([...p.querySelectorAll('[data-key]')].map(x=>[x.dataset.key,x.value])))};$$('input[id],select[id],textarea[id]').forEach(x=>data.fields[x.id]=x.value);localStorage.setItem('als-unit-builder-v1',JSON.stringify(data))}
function update(){const lua=generate();$('#lua').textContent=lua;const warnings=[];if(!val('unitName'))warnings.push('Add a unit name.');readUpgrades().forEach((u,i)=>{if(['cost','damage','range','spa'].some(k=>u[k]===''))warnings.push(`${i===0?'Deployment':`Upgrade ${i}`} is missing cost, damage, range, or SPA.`)});$('#warnings').textContent=warnings.join(' ');$('#summary').textContent=warnings.length?`${warnings.length} check${warnings.length>1?'s':''} needed.`:`${readUpgrades().length} rows · ready to copy`;save()}
function clearAll(){if(!confirm('Clear the saved unit and start again?'))return;localStorage.removeItem('als-unit-builder-v1');location.reload()}
function load(data){Object.entries(data.fields||{}).forEach(([k,v])=>{if($('#'+k))$('#'+k).value=v});$('#upgrades').innerHTML='';$('#passives').innerHTML='';(data.upgrades||[{}]).forEach(addUpgrade);(data.passives||[]).forEach(addPassive);update()}
function example(){load({fields:{unitName:'Berserker',rarity:'Mythic',element:'Dark',subtype:'Physical',towerType:'Hill',placement:'4',image:'Berserker-FB',caption:'No matter how hard it gets, I will keep moving forward.',overview:"'''Berserker''' is a {{Rarity|Mythic}} unit obtainable from [[Banners|Banner]]."},upgrades:[{cost:'600',damage:'37',range:'11',spa:'4',attack:'AoE (Cone)',burn:true},{cost:'1600',damage:'77',range:'12',spa:'4',attack:'AoE (Cone)',burn:true},{cost:'3600',damage:'155',range:'14',spa:'4',attack:'AoE (Circle)',text:'+ Fire Cannon',burn:true}],passives:[{name:'Battle Instinct',description:'This unit grows stronger as the battle continues.',upgrade:''}]})}
$('#addUpgrade').onclick=()=>addUpgrade();$('#addPassive').onclick=()=>addPassive();$('#clear').onclick=clearAll;$('#example').onclick=example;$('#copy').onclick=async()=>{await navigator.clipboard.writeText($('#lua').textContent);$('#copy').textContent='Copied!';setTimeout(()=>$('#copy').textContent='Copy Lua',1200)};$('#download').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([$('#lua').textContent],{type:'text/plain'}));a.download=(val('unitName')||'unit').replace(/[^a-z0-9-_]/gi,'-')+'.lua';a.click();URL.revokeObjectURL(a.href)};document.addEventListener('input',e=>{if(e.target.id)update()});try{const saved=JSON.parse(localStorage.getItem('als-unit-builder-v1'));saved?load(saved):addUpgrade()}catch{addUpgrade()}
