const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const FX=['burn','bleed','freeze','slow','crippled','hex','poison','black_flames','electrified'];
const FIELD_IDS=['name','rarity','element','subtype','tower','placement','image','caption','overview','ability_name','ability','ability_upgrade','ability_cooldown'];
const upgrades=$('#upgrades'),passives=$('#passives');
const value=id=>$('#'+id).value.trim();
const quote=v=>'"'+String(v??'').replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/\r?\n/g,'\\n')+'"';
const label=s=>s.split('_').map(x=>x[0].toUpperCase()+x.slice(1)).join(' ');
const numeric=v=>v===''?0:Number(v);
function upgradeRows(){return [...upgrades.children].map(card=>{const row={};card.querySelectorAll('[data-k]').forEach(x=>row[x.dataset.k]=x.value);FX.forEach(x=>row[x]=card.querySelector(`[data-effect="${x}"]`).checked);return row})}
function passiveRows(){return [...passives.children].map(card=>{const row={};card.querySelectorAll('[data-p]').forEach(x=>row[x.dataset.p]=x.value);return row})}
function renumber(){[...upgrades.children].forEach((c,i)=>c.querySelector('.upgrade-title').textContent=i===0?'Deployment (Upgrade 0)':`Upgrade ${i}`);[...passives.children].forEach((c,i)=>c.querySelector('.passive-num').textContent=i+1)}
function addUpgrade(data={}){const frag=$('#upgrade-template').content.cloneNode(true),card=frag.querySelector('.upgrade');card.querySelectorAll('[data-k]').forEach(x=>x.value=data[x.dataset.k]??'');FX.forEach(x=>card.querySelector(`[data-effect="${x}"]`).checked=!!data[x]);card.querySelector('.remove').onclick=()=>{card.remove();render()};card.querySelector('.copy-effects').onclick=()=>{const cards=[...upgrades.children],i=cards.indexOf(card);if(i>0)FX.forEach(x=>card.querySelector(`[data-effect="${x}"]`).checked=cards[i-1].querySelector(`[data-effect="${x}"]`).checked);render()};upgrades.append(card);renumber();render()}
function addPassive(data={}){const frag=$('#passive-template').content.cloneNode(true),card=frag.querySelector('.passive');card.querySelectorAll('[data-p]').forEach(x=>x.value=data[x.dataset.p]??'');card.querySelector('.remove').onclick=()=>{card.remove();render()};passives.append(card);renumber();render()}
function progression(rows,key){const vals=rows.map(r=>r[key]).filter(v=>v!=='');if(!vals.length)return'';const changes=vals.filter((v,i)=>i===0||v!==vals[i-1]);return changes.length===1?changes[0]:`${changes[0]} -> ${changes.at(-1)}`}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderPreview(rows,ps,used){const stats=[['Damage',progression(rows,'damage')||'—'],['Range',progression(rows,'range')||'—'],['SPA',progression(rows,'spa')||'—'],['Tower',value('tower')||'—'],['Element',value('element')||'—'],['Status',used.length?used.map(label).join(', '):'None'],['Deploy',numeric(rows[0]?.cost).toLocaleString('en-US')+'$'],['Total',rows.reduce((n,r)=>n+numeric(r.cost),0).toLocaleString('en-US')+'$']];const components=[...ps.map(p=>`<p><strong>${escapeHtml(p.name||'Passive')}:</strong> ${escapeHtml(p.description)}</p>`),...(value('ability_name')||value('ability')?[`<p><strong>${escapeHtml(value('ability_name')||'Ability')}:</strong> ${escapeHtml(value('ability'))}</p>`]:[])].join('');$('#unit-preview').innerHTML=`<article class="unit-preview-card"><div class="unit-preview-banner"><h3>${escapeHtml(value('name')||'Unit Name')}</h3><span class="rarity-pill">${escapeHtml(value('rarity'))}</span></div><div class="unit-preview-body">${value('caption')?`<p class="unit-preview-quote">“${escapeHtml(value('caption'))}”</p>`:''}<div class="unit-preview-stats">${stats.map(s=>`<div class="preview-stat"><span>${s[0]}</span><strong>${escapeHtml(s[1])}</strong></div>`).join('')}</div>${components?`<div class="preview-components">${components}</div>`:''}</div></article>`;$('#upgrade-preview').innerHTML=rows.length?`<h3 class="upgrade-preview-title">Upgrades</h3><div class="preview-upgrade-grid">${rows.map((r,i)=>`<article class="preview-upgrade"><h4><span>${i?'Upgrade '+i:'Deployment'}</span><span>${numeric(r.cost).toLocaleString('en-US')}$</span></h4><ul><li>Damage: ${escapeHtml(r.damage||'—')}</li><li>Range: ${escapeHtml(r.range||'—')}</li><li>SPA: ${escapeHtml(r.spa||'—')}</li><li>${escapeHtml(r.attack||'No AoE change')}</li></ul>${FX.some(x=>r[x])?`<div class="preview-effects">${FX.filter(x=>r[x]).map(label).join(' • ')}</div>`:''}</article>`).join('')}</div>`:'<p class="hint">Add an upgrade to preview it.</p>'}
function render(){renumber();const rows=upgradeRows(),ps=passiveRows().filter(p=>p.name||p.description),used=FX.filter(x=>rows.some(r=>r[x])),warnings=[];if(!value('name'))warnings.push('• Enter a unit name.');if(!rows.length)warnings.push('• Add at least one upgrade.');rows.forEach((r,i)=>['cost','damage','range','spa'].forEach(k=>{if(r[k]==='')warnings.push(`• ${i===0?'Deployment':'Upgrade '+i}: ${k} is missing.`)}));
 renderPreview(rows,ps,used);const status=used.length===0?quote('None'):used.length===1?quote(label(used[0])):'{'+used.map(x=>quote(label(x))).join(', ')+'}';
 const L=[`[${quote(value('name')||'Unit Name')}] = {`,`    rarity = ${quote(value('rarity'))},`,`    element = ${quote(value('element'))},`,`    subtype = ${quote(value('subtype'))},`,`    towertype = ${quote(value('tower'))},`,`    maxplacement = ${quote(value('placement'))},`,`    damage = ${quote(progression(rows,'damage'))},`,`    range = ${quote(progression(rows,'range'))},`,`    spa = ${quote(progression(rows,'spa'))},`,`    deploycost = ${quote(numeric(rows[0]?.cost).toLocaleString('en-US')+'$')},`,`    totalcost = ${quote(rows.reduce((n,r)=>n+numeric(r.cost),0).toLocaleString('en-US')+'$')},`,`    image = ${quote(value('image'))},`,`    statuseffect = ${status},`,`    aoetype = ${quote(progression(rows,'attack'))},`,`    imagecaption = ${quote(value('caption'))},`,`    overview = ${quote(value('overview'))},`];
 ps.forEach((p,i)=>{const n=i+1;L.push(`    passive${n}_name = ${quote(p.name)},`,`    passive${n} = ${quote(p.description)},`,`    passive${n}_upgrade = ${quote(p.upgrade)},`)});if(value('ability_name')||value('ability'))L.push(`    ability_name = ${quote(value('ability_name'))},`,`    ability = ${quote(value('ability'))},`,`    ability_upgrade = ${quote(value('ability_upgrade'))},`,`    ability_cooldown = ${quote(value('ability_cooldown'))},`);L.push('    upgrades = {');
 rows.forEach((r,i)=>{const parts=[`upgrade_cost = ${numeric(r.cost)}`,`damage = ${numeric(r.damage)}`,`range = ${numeric(r.range)}`,`spa = ${numeric(r.spa)}`];if(i===0)parts.push(`placement = ${numeric(value('placement'))}`,`tower_type = ${quote(value('tower'))}`,`attack_type = ${quote(r.attack)}`);else if(r.attack&&r.attack!==rows[i-1]?.attack)parts.push(`aoe_change = ${quote(r.attack)}`);if(r.text)parts.push(`text_line_1 = ${quote(r.text)}`);FX.filter(x=>r[x]).forEach(x=>parts.push(`${x} = "yes"`));L.push(`        { ${parts.join(', ')}},`)});L.push('    },','},');$('#output').textContent=L.join('\n');$('#warnings').textContent=warnings.join('\n');$('#status').textContent=warnings.length?`${warnings.length} item${warnings.length===1?'':'s'} to check`:'Ready to copy';localStorage.setItem('als-unit-template-v1',JSON.stringify({fields:Object.fromEntries(FIELD_IDS.map(id=>[id,value(id)])),upgrades:rows,passives:passiveRows()}))}
document.addEventListener('input',render);$('#add-upgrade').onclick=()=>addUpgrade();$('#add-passive').onclick=()=>addPassive();$('#copy').onclick=async()=>{await navigator.clipboard.writeText($('#output').textContent);$('#copy').textContent='Copied!';setTimeout(()=>$('#copy').textContent='Copy Lua',1200)};$('#download').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([$('#output').textContent],{type:'text/plain'}));a.download=(value('name')||'unit').replace(/[^a-z0-9_-]+/gi,'_')+'.lua';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0)};
$('#show-preview').onclick=()=>{$('#visual-preview').hidden=false;$('#output').hidden=true;$('#show-preview').classList.add('active');$('#show-lua').classList.remove('active')};$('#show-lua').onclick=()=>{$('#visual-preview').hidden=true;$('#output').hidden=false;$('#show-lua').classList.add('active');$('#show-preview').classList.remove('active')};
function loadExample(){Object.entries({name:'Berserker',rarity:'Mythic',element:'Dark',subtype:'Physical',tower:'Hill',placement:'4',image:'Berserker-FB',caption:'A sample unit.',overview:"'''Berserker''' is a sample unit.",ability_name:'Rage',ability:'Temporarily increases damage.',ability_upgrade:'4',ability_cooldown:'120'}).forEach(([k,v])=>$('#'+k).value=v);upgrades.innerHTML='';passives.innerHTML='';addPassive({name:'Battle Fury',description:'Gains <number>10%</number> damage after defeating an enemy.',upgrade:''});addUpgrade({cost:600,damage:37,range:11,spa:4,attack:'AoE (Cone)',burn:true});addUpgrade({cost:1600,damage:77,range:12,spa:4,burn:true});addUpgrade({cost:3070,damage:125,range:13,spa:4,burn:true,text:'+ Fire Cannon',attack:'AoE (Circle)'})}$('#example').onclick=loadExample;$('#clear').onclick=()=>{if(!confirm('Clear all saved unit data?'))return;localStorage.removeItem('als-unit-template-v1');FIELD_IDS.forEach(id=>$('#'+id).value='');$('#rarity').value='Mythic';$('#subtype').value='Physical';$('#tower').value='Ground';$('#placement').value='4';upgrades.innerHTML='';passives.innerHTML='';addUpgrade()};
try{const saved=JSON.parse(localStorage.getItem('als-unit-template-v1'));if(saved){Object.entries(saved.fields||{}).forEach(([k,v])=>{if($('#'+k))$('#'+k).value=v});(saved.passives||[]).forEach(addPassive);(saved.upgrades||[]).forEach(addUpgrade)}else addUpgrade()}catch{addUpgrade()}render();
