const $=s=>document.querySelector(s),box=$('#upgrades'),FX=['burn','bleed','freeze','slow','crippled','hex'];
const val=id=>$('#'+id).value.trim(),q=v=>'"'+String(v||'').replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/\n/g,'\\n')+'"';
function rows(){return [...box.children].map(a=>{let r={};a.querySelectorAll('[data-k]').forEach(x=>r[x.dataset.k]=x.value);FX.forEach(e=>r[e]=a.querySelector(`[data-effect=${e}]`).checked);return r})}
function renumber(){[...box.children].forEach((a,i)=>a.querySelector('.num').textContent=i)}
function add(d={}){let f=$('#upgrade').content.cloneNode(true),a=f.querySelector('.upgrade');a.querySelectorAll('[data-k]').forEach(x=>x.value=d[x.dataset.k]??'');FX.forEach(e=>a.querySelector(`[data-effect=${e}]`).checked=!!d[e]);a.querySelector('.remove').onclick=()=>{a.remove();render()};box.append(a);renumber();render()}
function span(rs,k){let a=rs.map(r=>r[k]).filter(Boolean);return a.length?a[0]+(a.at(-1)!=a[0]?' -> '+a.at(-1):''):''}
function render(){
 renumber();let rs=rows(),used=FX.filter(e=>rs.some(r=>r[e])),status=used.length?used.map(e=>e[0].toUpperCase()+e.slice(1)):['None'];
 let L=[`[${q(val('name')||'Unit Name')}] = {`,`    rarity = ${q(val('rarity'))},`,`    element = ${q(val('element'))},`,`    subtype = ${q(val('subtype'))},`,`    towertype = ${q(val('tower'))},`,`    maxplacement = ${q(val('placement'))},`,`    damage = ${q(span(rs,'damage'))},`,`    range = ${q(span(rs,'range'))},`,`    spa = ${q(span(rs,'spa'))},`,`    deploycost = ${q(Number(rs[0]?.cost||0).toLocaleString()+'$')},`,`    totalcost = ${q(rs.reduce((s,r)=>s+Number(r.cost||0),0).toLocaleString()+'$')},`,`    image = ${q(val('image'))},`,`    statuseffect = ${status.length===1?q(status[0]):'{'+status.map(q).join(', ')+'}'},`,`    aoetype = ${q(span(rs,'attack'))},`,`    imagecaption = ${q(val('caption'))},`,`    overview = ${q(val('overview'))},`,`    upgrades = {`];
 rs.forEach((r,i)=>{let p=[`upgrade_cost = ${Number(r.cost||0)}`,`damage = ${Number(r.damage||0)}`,`range = ${Number(r.range||0)}`,`spa = ${Number(r.spa||0)}`];if(i===0)p.push(`placement = ${Number(val('placement')||0)}`,`tower_type = ${q(val('tower'))}`,`attack_type = ${q(r.attack)}`);else if(r.attack)p.push(`aoe_change = ${q(r.attack)}`);if(r.text)p.push(`text_line_1 = ${q(r.text)}`);FX.filter(e=>r[e]).forEach(e=>p.push(`${e} = "yes"`));L.push(`        { ${p.join(', ')}},`)});
 L.push('    },','},');$('#output').textContent=L.join('\n');$('#warnings').textContent=(!val('name')?'Enter a unit name. ':'')+(!rs.length?'Add at least one upgrade.':'');localStorage.setItem('als-unit-template',JSON.stringify({fields:Object.fromEntries(['name','rarity','element','subtype','tower','placement','image','caption','overview'].map(k=>[k,val(k)])),rows:rs}))
}
document.addEventListener('input',render);$('#add').onclick=()=>add();$('#copy').onclick=async()=>{await navigator.clipboard.writeText($('#output').textContent);$('#copy').textContent='Copied!';setTimeout(()=>$('#copy').textContent='Copy Lua',1000)};
$('#download').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([$('#output').textContent]));a.download=(val('name')||'unit').replace(/\W+/g,'_')+'.lua';a.click()};
$('#example').onclick=()=>{Object.entries({name:'Berserker',rarity:'Mythic',element:'Dark',subtype:'Physical',tower:'Hill',placement:'4',image:'Berserker-FB'}).forEach(([k,v])=>$('#'+k).value=v);box.innerHTML='';add({cost:600,damage:37,range:11,spa:4,attack:'AoE (Cone)',burn:true});add({cost:1600,damage:77,range:12,spa:4,burn:true})};
try{let s=JSON.parse(localStorage.getItem('als-unit-template'));if(s){Object.entries(s.fields||{}).forEach(([k,v])=>$('#'+k).value=v);(s.rows||[]).forEach(add)}else add()}catch{add()}render();
